2018-07-17 15:22:16,439 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
2018-07-17 15:25:26,893 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
2018-07-17 15:25:26,896 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
2018-07-17 15:25:26,896 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
2018-07-17 15:25:38,535 ERROR: Exception on /user/manish [GET] [in /home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/mani/work/next upload/basic-webapp/app/main/routes.py", line 69, in user
    next_url=next_url, prev_url=prev_url)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mani/work/next upload/basic-webapp/app/templates/user.html", line 59, in top-level template code
    {% block app_content %}
  File "/home/mani/work/next upload/basic-webapp/app/templates/user.html", line 76, in block "app_content"
    {% include '_post.html' %}
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2018-07-17 15:25:38,535 ERROR: Exception on /user/manish [GET] [in /home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/mani/work/next upload/basic-webapp/app/main/routes.py", line 69, in user
    next_url=next_url, prev_url=prev_url)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mani/work/next upload/basic-webapp/app/templates/user.html", line 59, in top-level template code
    {% block app_content %}
  File "/home/mani/work/next upload/basic-webapp/app/templates/user.html", line 76, in block "app_content"
    {% include '_post.html' %}
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/mani/work/next upload/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2018-07-17 15:26:22,459 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
2018-07-17 15:26:22,463 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
2018-07-17 15:26:22,463 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
2018-07-17 15:28:21,262 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
2018-07-17 15:28:21,266 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
2018-07-17 15:28:21,266 INFO: M.S.Blog startup [in /home/mani/work/next upload/basic-webapp/app/__init__.py:77]
